# Generated by Django 3.0.5 on 2024-03-19 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Date')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Location')),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, verbose_name='Email Address')),
                ('referrer', models.CharField(blank=True, max_length=255, null=True, verbose_name='Referrer')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('your_message', models.TextField(blank=True, null=True, verbose_name='Message')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('wedding', 'Wedding'), ('haldi', 'Haldi'), ('birthday', 'Birthday')], max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='studio.Project')),
            ],
        ),
    ]
